version: '2'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ups_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  proj:
    user: root
    build: .
    volumes:
      - .:/deploy
    ports:
      - "13579:13579"
    depends_on:
      - db