// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.erss.ups.proto.UPStoAmazon;

/**
 * Protobuf type {@code tutorial.AmazonPick}
 */
public final class AmazonPick extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.AmazonPick)
    AmazonPickOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AmazonPick.newBuilder() to construct.
  private AmazonPick(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AmazonPick() {
    upsAccount_ = "";
    things_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AmazonPick();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.erss.ups.proto.UPStoAmazon.WithAmazon.internal_static_tutorial_AmazonPick_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.erss.ups.proto.UPStoAmazon.WithAmazon.internal_static_tutorial_AmazonPick_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.class, edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.Builder.class);
  }

  private int bitField0_;
  public static final int SHIPID_FIELD_NUMBER = 1;
  private long shipid_;
  /**
   * <pre>
   * package id / order id
   * </pre>
   *
   * <code>required int64 shipid = 1;</code>
   * @return Whether the shipid field is set.
   */
  @java.lang.Override
  public boolean hasShipid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * package id / order id
   * </pre>
   *
   * <code>required int64 shipid = 1;</code>
   * @return The shipid.
   */
  @java.lang.Override
  public long getShipid() {
    return shipid_;
  }

  public static final int X_FIELD_NUMBER = 2;
  private int x_;
  /**
   * <pre>
   * destination x
   * </pre>
   *
   * <code>required int32 x = 2;</code>
   * @return Whether the x field is set.
   */
  @java.lang.Override
  public boolean hasX() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * destination x
   * </pre>
   *
   * <code>required int32 x = 2;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private int y_;
  /**
   * <pre>
   * destination y
   * </pre>
   *
   * <code>required int32 y = 3;</code>
   * @return Whether the y field is set.
   */
  @java.lang.Override
  public boolean hasY() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * destination y
   * </pre>
   *
   * <code>required int32 y = 3;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int WHNUM_FIELD_NUMBER = 4;
  private int whnum_;
  /**
   * <pre>
   * warehouse id
   * </pre>
   *
   * <code>required int32 whnum = 4;</code>
   * @return Whether the whnum field is set.
   */
  @java.lang.Override
  public boolean hasWhnum() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * warehouse id
   * </pre>
   *
   * <code>required int32 whnum = 4;</code>
   * @return The whnum.
   */
  @java.lang.Override
  public int getWhnum() {
    return whnum_;
  }

  public static final int SEQ_FIELD_NUMBER = 5;
  private long seq_;
  /**
   * <code>required int64 seq = 5;</code>
   * @return Whether the seq field is set.
   */
  @java.lang.Override
  public boolean hasSeq() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required int64 seq = 5;</code>
   * @return The seq.
   */
  @java.lang.Override
  public long getSeq() {
    return seq_;
  }

  public static final int UPSACCOUNT_FIELD_NUMBER = 6;
  private volatile java.lang.Object upsAccount_;
  /**
   * <code>optional string upsAccount = 6;</code>
   * @return Whether the upsAccount field is set.
   */
  @java.lang.Override
  public boolean hasUpsAccount() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string upsAccount = 6;</code>
   * @return The upsAccount.
   */
  @java.lang.Override
  public java.lang.String getUpsAccount() {
    java.lang.Object ref = upsAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        upsAccount_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string upsAccount = 6;</code>
   * @return The bytes for upsAccount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpsAccountBytes() {
    java.lang.Object ref = upsAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      upsAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WHX_FIELD_NUMBER = 7;
  private int whx_;
  /**
   * <code>required int32 whx = 7;</code>
   * @return Whether the whx field is set.
   */
  @java.lang.Override
  public boolean hasWhx() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>required int32 whx = 7;</code>
   * @return The whx.
   */
  @java.lang.Override
  public int getWhx() {
    return whx_;
  }

  public static final int WHY_FIELD_NUMBER = 8;
  private int why_;
  /**
   * <code>required int32 why = 8;</code>
   * @return Whether the why field is set.
   */
  @java.lang.Override
  public boolean hasWhy() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>required int32 why = 8;</code>
   * @return The why.
   */
  @java.lang.Override
  public int getWhy() {
    return why_;
  }

  public static final int THINGS_FIELD_NUMBER = 9;
  private java.util.List<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct> things_;
  /**
   * <code>repeated .tutorial.UAProduct things = 9;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct> getThingsList() {
    return things_;
  }
  /**
   * <code>repeated .tutorial.UAProduct things = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder> 
      getThingsOrBuilderList() {
    return things_;
  }
  /**
   * <code>repeated .tutorial.UAProduct things = 9;</code>
   */
  @java.lang.Override
  public int getThingsCount() {
    return things_.size();
  }
  /**
   * <code>repeated .tutorial.UAProduct things = 9;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoAmazon.UAProduct getThings(int index) {
    return things_.get(index);
  }
  /**
   * <code>repeated .tutorial.UAProduct things = 9;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder getThingsOrBuilder(
      int index) {
    return things_.get(index);
  }

  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.AmazonPick}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.AmazonPick)
      edu.duke.erss.ups.proto.UPStoAmazon.AmazonPickOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.erss.ups.proto.UPStoAmazon.WithAmazon.internal_static_tutorial_AmazonPick_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.erss.ups.proto.UPStoAmazon.WithAmazon.internal_static_tutorial_AmazonPick_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.class, edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.Builder.class);
    }

    // Construct using edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getThingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      shipid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      whnum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      seq_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      upsAccount_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      whx_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      why_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      if (thingsBuilder_ == null) {
        things_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        thingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.erss.ups.proto.UPStoAmazon.WithAmazon.internal_static_tutorial_AmazonPick_descriptor;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick getDefaultInstanceForType() {
      return edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick build() {
      edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick buildPartial() {
      edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick result = new edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.shipid_ = shipid_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y_ = y_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.whnum_ = whnum_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.seq_ = seq_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.upsAccount_ = upsAccount_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.whx_ = whx_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.why_ = why_;
        to_bitField0_ |= 0x00000080;
      }
      if (thingsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          things_ = java.util.Collections.unmodifiableList(things_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.things_ = things_;
      } else {
        result.things_ = thingsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private long shipid_ ;
    /**
     * <pre>
     * package id / order id
     * </pre>
     *
     * <code>required int64 shipid = 1;</code>
     * @return Whether the shipid field is set.
     */
    @java.lang.Override
    public boolean hasShipid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * package id / order id
     * </pre>
     *
     * <code>required int64 shipid = 1;</code>
     * @return The shipid.
     */
    @java.lang.Override
    public long getShipid() {
      return shipid_;
    }
    /**
     * <pre>
     * package id / order id
     * </pre>
     *
     * <code>required int64 shipid = 1;</code>
     * @param value The shipid to set.
     * @return This builder for chaining.
     */
    public Builder setShipid(long value) {
      bitField0_ |= 0x00000001;
      shipid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * package id / order id
     * </pre>
     *
     * <code>required int64 shipid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShipid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      shipid_ = 0L;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <pre>
     * destination x
     * </pre>
     *
     * <code>required int32 x = 2;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * destination x
     * </pre>
     *
     * <code>required int32 x = 2;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <pre>
     * destination x
     * </pre>
     *
     * <code>required int32 x = 2;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {
      bitField0_ |= 0x00000002;
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * destination x
     * </pre>
     *
     * <code>required int32 x = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <pre>
     * destination y
     * </pre>
     *
     * <code>required int32 y = 3;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * destination y
     * </pre>
     *
     * <code>required int32 y = 3;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <pre>
     * destination y
     * </pre>
     *
     * <code>required int32 y = 3;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {
      bitField0_ |= 0x00000004;
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * destination y
     * </pre>
     *
     * <code>required int32 y = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y_ = 0;
      onChanged();
      return this;
    }

    private int whnum_ ;
    /**
     * <pre>
     * warehouse id
     * </pre>
     *
     * <code>required int32 whnum = 4;</code>
     * @return Whether the whnum field is set.
     */
    @java.lang.Override
    public boolean hasWhnum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * warehouse id
     * </pre>
     *
     * <code>required int32 whnum = 4;</code>
     * @return The whnum.
     */
    @java.lang.Override
    public int getWhnum() {
      return whnum_;
    }
    /**
     * <pre>
     * warehouse id
     * </pre>
     *
     * <code>required int32 whnum = 4;</code>
     * @param value The whnum to set.
     * @return This builder for chaining.
     */
    public Builder setWhnum(int value) {
      bitField0_ |= 0x00000008;
      whnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * warehouse id
     * </pre>
     *
     * <code>required int32 whnum = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhnum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      whnum_ = 0;
      onChanged();
      return this;
    }

    private long seq_ ;
    /**
     * <code>required int64 seq = 5;</code>
     * @return Whether the seq field is set.
     */
    @java.lang.Override
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int64 seq = 5;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return seq_;
    }
    /**
     * <code>required int64 seq = 5;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {
      bitField0_ |= 0x00000010;
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 seq = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      bitField0_ = (bitField0_ & ~0x00000010);
      seq_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object upsAccount_ = "";
    /**
     * <code>optional string upsAccount = 6;</code>
     * @return Whether the upsAccount field is set.
     */
    public boolean hasUpsAccount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string upsAccount = 6;</code>
     * @return The upsAccount.
     */
    public java.lang.String getUpsAccount() {
      java.lang.Object ref = upsAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          upsAccount_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string upsAccount = 6;</code>
     * @return The bytes for upsAccount.
     */
    public com.google.protobuf.ByteString
        getUpsAccountBytes() {
      java.lang.Object ref = upsAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upsAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string upsAccount = 6;</code>
     * @param value The upsAccount to set.
     * @return This builder for chaining.
     */
    public Builder setUpsAccount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      upsAccount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsAccount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpsAccount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      upsAccount_ = getDefaultInstance().getUpsAccount();
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsAccount = 6;</code>
     * @param value The bytes for upsAccount to set.
     * @return This builder for chaining.
     */
    public Builder setUpsAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      upsAccount_ = value;
      onChanged();
      return this;
    }

    private int whx_ ;
    /**
     * <code>required int32 whx = 7;</code>
     * @return Whether the whx field is set.
     */
    @java.lang.Override
    public boolean hasWhx() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required int32 whx = 7;</code>
     * @return The whx.
     */
    @java.lang.Override
    public int getWhx() {
      return whx_;
    }
    /**
     * <code>required int32 whx = 7;</code>
     * @param value The whx to set.
     * @return This builder for chaining.
     */
    public Builder setWhx(int value) {
      bitField0_ |= 0x00000040;
      whx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 whx = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhx() {
      bitField0_ = (bitField0_ & ~0x00000040);
      whx_ = 0;
      onChanged();
      return this;
    }

    private int why_ ;
    /**
     * <code>required int32 why = 8;</code>
     * @return Whether the why field is set.
     */
    @java.lang.Override
    public boolean hasWhy() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>required int32 why = 8;</code>
     * @return The why.
     */
    @java.lang.Override
    public int getWhy() {
      return why_;
    }
    /**
     * <code>required int32 why = 8;</code>
     * @param value The why to set.
     * @return This builder for chaining.
     */
    public Builder setWhy(int value) {
      bitField0_ |= 0x00000080;
      why_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 why = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhy() {
      bitField0_ = (bitField0_ & ~0x00000080);
      why_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct> things_ =
      java.util.Collections.emptyList();
    private void ensureThingsIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        things_ = new java.util.ArrayList<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct>(things_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.UPStoAmazon.UAProduct, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder, edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder> thingsBuilder_;

    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct> getThingsList() {
      if (thingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(things_);
      } else {
        return thingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public int getThingsCount() {
      if (thingsBuilder_ == null) {
        return things_.size();
      } else {
        return thingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public edu.duke.erss.ups.proto.UPStoAmazon.UAProduct getThings(int index) {
      if (thingsBuilder_ == null) {
        return things_.get(index);
      } else {
        return thingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder setThings(
        int index, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.set(index, value);
        onChanged();
      } else {
        thingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder setThings(
        int index, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.set(index, builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder addThings(edu.duke.erss.ups.proto.UPStoAmazon.UAProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.add(value);
        onChanged();
      } else {
        thingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder addThings(
        int index, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.add(index, value);
        onChanged();
      } else {
        thingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder addThings(
        edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.add(builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder addThings(
        int index, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.add(index, builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder addAllThings(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.UPStoAmazon.UAProduct> values) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, things_);
        onChanged();
      } else {
        thingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder clearThings() {
      if (thingsBuilder_ == null) {
        things_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        thingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public Builder removeThings(int index) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.remove(index);
        onChanged();
      } else {
        thingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder getThingsBuilder(
        int index) {
      return getThingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder getThingsOrBuilder(
        int index) {
      if (thingsBuilder_ == null) {
        return things_.get(index);  } else {
        return thingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder> 
         getThingsOrBuilderList() {
      if (thingsBuilder_ != null) {
        return thingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(things_);
      }
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder addThingsBuilder() {
      return getThingsFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder addThingsBuilder(
        int index) {
      return getThingsFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.UAProduct things = 9;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder> 
         getThingsBuilderList() {
      return getThingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.UPStoAmazon.UAProduct, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder, edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder> 
        getThingsFieldBuilder() {
      if (thingsBuilder_ == null) {
        thingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.UPStoAmazon.UAProduct, edu.duke.erss.ups.proto.UPStoAmazon.UAProduct.Builder, edu.duke.erss.ups.proto.UPStoAmazon.UAProductOrBuilder>(
                things_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        things_ = null;
      }
      return thingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.AmazonPick)
  }

  // @@protoc_insertion_point(class_scope:tutorial.AmazonPick)
  private static final edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick();
  }

  public static edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AmazonPick>
      PARSER = new com.google.protobuf.AbstractParser<AmazonPick>() {
    @java.lang.Override
    public AmazonPick parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AmazonPick> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AmazonPick> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoAmazon.AmazonPick getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

