// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.erss.ups.proto.UPStoAmazon;

public interface UAConnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.UAConnect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 worldid = 1;</code>
   * @return Whether the worldid field is set.
   */
  boolean hasWorldid();
  /**
   * <code>required int64 worldid = 1;</code>
   * @return The worldid.
   */
  long getWorldid();
}
