// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_amazon.proto

package edu.duke.erss.ups.proto.AmazontoWorld;

/**
 * Protobuf type {@code ACommands}
 */
public final class ACommands extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ACommands)
    ACommandsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ACommands.newBuilder() to construct.
  private ACommands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ACommands() {
    buy_ = java.util.Collections.emptyList();
    topack_ = java.util.Collections.emptyList();
    load_ = java.util.Collections.emptyList();
    queries_ = java.util.Collections.emptyList();
    acks_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ACommands();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_ACommands_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_ACommands_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.erss.ups.proto.AmazontoWorld.ACommands.class, edu.duke.erss.ups.proto.AmazontoWorld.ACommands.Builder.class);
  }

  private int bitField0_;
  public static final int BUY_FIELD_NUMBER = 1;
  private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> buy_;
  /**
   * <code>repeated .APurchaseMore buy = 1;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> getBuyList() {
    return buy_;
  }
  /**
   * <code>repeated .APurchaseMore buy = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder> 
      getBuyOrBuilderList() {
    return buy_;
  }
  /**
   * <code>repeated .APurchaseMore buy = 1;</code>
   */
  @java.lang.Override
  public int getBuyCount() {
    return buy_.size();
  }
  /**
   * <code>repeated .APurchaseMore buy = 1;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getBuy(int index) {
    return buy_.get(index);
  }
  /**
   * <code>repeated .APurchaseMore buy = 1;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder getBuyOrBuilder(
      int index) {
    return buy_.get(index);
  }

  public static final int TOPACK_FIELD_NUMBER = 2;
  private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APack> topack_;
  /**
   * <code>repeated .APack topack = 2;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APack> getTopackList() {
    return topack_;
  }
  /**
   * <code>repeated .APack topack = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder> 
      getTopackOrBuilderList() {
    return topack_;
  }
  /**
   * <code>repeated .APack topack = 2;</code>
   */
  @java.lang.Override
  public int getTopackCount() {
    return topack_.size();
  }
  /**
   * <code>repeated .APack topack = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APack getTopack(int index) {
    return topack_.get(index);
  }
  /**
   * <code>repeated .APack topack = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder getTopackOrBuilder(
      int index) {
    return topack_.get(index);
  }

  public static final int LOAD_FIELD_NUMBER = 3;
  private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck> load_;
  /**
   * <code>repeated .APutOnTruck load = 3;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck> getLoadList() {
    return load_;
  }
  /**
   * <code>repeated .APutOnTruck load = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder> 
      getLoadOrBuilderList() {
    return load_;
  }
  /**
   * <code>repeated .APutOnTruck load = 3;</code>
   */
  @java.lang.Override
  public int getLoadCount() {
    return load_.size();
  }
  /**
   * <code>repeated .APutOnTruck load = 3;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck getLoad(int index) {
    return load_.get(index);
  }
  /**
   * <code>repeated .APutOnTruck load = 3;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder getLoadOrBuilder(
      int index) {
    return load_.get(index);
  }

  public static final int QUERIES_FIELD_NUMBER = 4;
  private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AQuery> queries_;
  /**
   * <code>repeated .AQuery queries = 4;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AQuery> getQueriesList() {
    return queries_;
  }
  /**
   * <code>repeated .AQuery queries = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder> 
      getQueriesOrBuilderList() {
    return queries_;
  }
  /**
   * <code>repeated .AQuery queries = 4;</code>
   */
  @java.lang.Override
  public int getQueriesCount() {
    return queries_.size();
  }
  /**
   * <code>repeated .AQuery queries = 4;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.AQuery getQueries(int index) {
    return queries_.get(index);
  }
  /**
   * <code>repeated .AQuery queries = 4;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder getQueriesOrBuilder(
      int index) {
    return queries_.get(index);
  }

  public static final int SIMSPEED_FIELD_NUMBER = 5;
  private int simspeed_;
  /**
   * <code>optional uint32 simspeed = 5;</code>
   * @return Whether the simspeed field is set.
   */
  @java.lang.Override
  public boolean hasSimspeed() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 simspeed = 5;</code>
   * @return The simspeed.
   */
  @java.lang.Override
  public int getSimspeed() {
    return simspeed_;
  }

  public static final int DISCONNECT_FIELD_NUMBER = 6;
  private boolean disconnect_;
  /**
   * <code>optional bool disconnect = 6;</code>
   * @return Whether the disconnect field is set.
   */
  @java.lang.Override
  public boolean hasDisconnect() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool disconnect = 6;</code>
   * @return The disconnect.
   */
  @java.lang.Override
  public boolean getDisconnect() {
    return disconnect_;
  }

  public static final int ACKS_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.LongList acks_;
  /**
   * <code>repeated int64 acks = 7;</code>
   * @return A list containing the acks.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getAcksList() {
    return acks_;
  }
  /**
   * <code>repeated int64 acks = 7;</code>
   * @return The count of acks.
   */
  public int getAcksCount() {
    return acks_.size();
  }
  /**
   * <code>repeated int64 acks = 7;</code>
   * @param index The index of the element to return.
   * @return The acks at the given index.
   */
  public long getAcks(int index) {
    return acks_.getLong(index);
  }

  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.erss.ups.proto.AmazontoWorld.ACommands prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ACommands}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ACommands)
      edu.duke.erss.ups.proto.AmazontoWorld.ACommandsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_ACommands_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_ACommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.erss.ups.proto.AmazontoWorld.ACommands.class, edu.duke.erss.ups.proto.AmazontoWorld.ACommands.Builder.class);
    }

    // Construct using edu.duke.erss.ups.proto.AmazontoWorld.ACommands.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBuyFieldBuilder();
        getTopackFieldBuilder();
        getLoadFieldBuilder();
        getQueriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (buyBuilder_ == null) {
        buy_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        buyBuilder_.clear();
      }
      if (topackBuilder_ == null) {
        topack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        topackBuilder_.clear();
      }
      if (loadBuilder_ == null) {
        load_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        loadBuilder_.clear();
      }
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        queriesBuilder_.clear();
      }
      simspeed_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      disconnect_ = false;
      bitField0_ = (bitField0_ & ~0x00000020);
      acks_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_ACommands_descriptor;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.ACommands getDefaultInstanceForType() {
      return edu.duke.erss.ups.proto.AmazontoWorld.ACommands.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.ACommands build() {
      edu.duke.erss.ups.proto.AmazontoWorld.ACommands result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.ACommands buildPartial() {
      edu.duke.erss.ups.proto.AmazontoWorld.ACommands result = new edu.duke.erss.ups.proto.AmazontoWorld.ACommands(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (buyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          buy_ = java.util.Collections.unmodifiableList(buy_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.buy_ = buy_;
      } else {
        result.buy_ = buyBuilder_.build();
      }
      if (topackBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          topack_ = java.util.Collections.unmodifiableList(topack_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.topack_ = topack_;
      } else {
        result.topack_ = topackBuilder_.build();
      }
      if (loadBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          load_ = java.util.Collections.unmodifiableList(load_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.load_ = load_;
      } else {
        result.load_ = loadBuilder_.build();
      }
      if (queriesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          queries_ = java.util.Collections.unmodifiableList(queries_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.queries_ = queries_;
      } else {
        result.queries_ = queriesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.simspeed_ = simspeed_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.disconnect_ = disconnect_;
        to_bitField0_ |= 0x00000002;
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        acks_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.acks_ = acks_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> buy_ =
      java.util.Collections.emptyList();
    private void ensureBuyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        buy_ = new java.util.ArrayList<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore>(buy_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder> buyBuilder_;

    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> getBuyList() {
      if (buyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(buy_);
      } else {
        return buyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public int getBuyCount() {
      if (buyBuilder_ == null) {
        return buy_.size();
      } else {
        return buyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getBuy(int index) {
      if (buyBuilder_ == null) {
        return buy_.get(index);
      } else {
        return buyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder setBuy(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore value) {
      if (buyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyIsMutable();
        buy_.set(index, value);
        onChanged();
      } else {
        buyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder setBuy(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder builderForValue) {
      if (buyBuilder_ == null) {
        ensureBuyIsMutable();
        buy_.set(index, builderForValue.build());
        onChanged();
      } else {
        buyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder addBuy(edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore value) {
      if (buyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyIsMutable();
        buy_.add(value);
        onChanged();
      } else {
        buyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder addBuy(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore value) {
      if (buyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyIsMutable();
        buy_.add(index, value);
        onChanged();
      } else {
        buyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder addBuy(
        edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder builderForValue) {
      if (buyBuilder_ == null) {
        ensureBuyIsMutable();
        buy_.add(builderForValue.build());
        onChanged();
      } else {
        buyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder addBuy(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder builderForValue) {
      if (buyBuilder_ == null) {
        ensureBuyIsMutable();
        buy_.add(index, builderForValue.build());
        onChanged();
      } else {
        buyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder addAllBuy(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> values) {
      if (buyBuilder_ == null) {
        ensureBuyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, buy_);
        onChanged();
      } else {
        buyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder clearBuy() {
      if (buyBuilder_ == null) {
        buy_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        buyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public Builder removeBuy(int index) {
      if (buyBuilder_ == null) {
        ensureBuyIsMutable();
        buy_.remove(index);
        onChanged();
      } else {
        buyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder getBuyBuilder(
        int index) {
      return getBuyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder getBuyOrBuilder(
        int index) {
      if (buyBuilder_ == null) {
        return buy_.get(index);  } else {
        return buyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder> 
         getBuyOrBuilderList() {
      if (buyBuilder_ != null) {
        return buyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(buy_);
      }
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder addBuyBuilder() {
      return getBuyFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.getDefaultInstance());
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder addBuyBuilder(
        int index) {
      return getBuyFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.getDefaultInstance());
    }
    /**
     * <code>repeated .APurchaseMore buy = 1;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder> 
         getBuyBuilderList() {
      return getBuyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder> 
        getBuyFieldBuilder() {
      if (buyBuilder_ == null) {
        buyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder>(
                buy_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        buy_ = null;
      }
      return buyBuilder_;
    }

    private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APack> topack_ =
      java.util.Collections.emptyList();
    private void ensureTopackIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        topack_ = new java.util.ArrayList<edu.duke.erss.ups.proto.AmazontoWorld.APack>(topack_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APack, edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder> topackBuilder_;

    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APack> getTopackList() {
      if (topackBuilder_ == null) {
        return java.util.Collections.unmodifiableList(topack_);
      } else {
        return topackBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public int getTopackCount() {
      if (topackBuilder_ == null) {
        return topack_.size();
      } else {
        return topackBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APack getTopack(int index) {
      if (topackBuilder_ == null) {
        return topack_.get(index);
      } else {
        return topackBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder setTopack(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APack value) {
      if (topackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopackIsMutable();
        topack_.set(index, value);
        onChanged();
      } else {
        topackBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder setTopack(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder builderForValue) {
      if (topackBuilder_ == null) {
        ensureTopackIsMutable();
        topack_.set(index, builderForValue.build());
        onChanged();
      } else {
        topackBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder addTopack(edu.duke.erss.ups.proto.AmazontoWorld.APack value) {
      if (topackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopackIsMutable();
        topack_.add(value);
        onChanged();
      } else {
        topackBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder addTopack(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APack value) {
      if (topackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopackIsMutable();
        topack_.add(index, value);
        onChanged();
      } else {
        topackBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder addTopack(
        edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder builderForValue) {
      if (topackBuilder_ == null) {
        ensureTopackIsMutable();
        topack_.add(builderForValue.build());
        onChanged();
      } else {
        topackBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder addTopack(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder builderForValue) {
      if (topackBuilder_ == null) {
        ensureTopackIsMutable();
        topack_.add(index, builderForValue.build());
        onChanged();
      } else {
        topackBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder addAllTopack(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.AmazontoWorld.APack> values) {
      if (topackBuilder_ == null) {
        ensureTopackIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, topack_);
        onChanged();
      } else {
        topackBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder clearTopack() {
      if (topackBuilder_ == null) {
        topack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        topackBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public Builder removeTopack(int index) {
      if (topackBuilder_ == null) {
        ensureTopackIsMutable();
        topack_.remove(index);
        onChanged();
      } else {
        topackBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder getTopackBuilder(
        int index) {
      return getTopackFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder getTopackOrBuilder(
        int index) {
      if (topackBuilder_ == null) {
        return topack_.get(index);  } else {
        return topackBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder> 
         getTopackOrBuilderList() {
      if (topackBuilder_ != null) {
        return topackBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(topack_);
      }
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder addTopackBuilder() {
      return getTopackFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.AmazontoWorld.APack.getDefaultInstance());
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder addTopackBuilder(
        int index) {
      return getTopackFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.AmazontoWorld.APack.getDefaultInstance());
    }
    /**
     * <code>repeated .APack topack = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder> 
         getTopackBuilderList() {
      return getTopackFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APack, edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder> 
        getTopackFieldBuilder() {
      if (topackBuilder_ == null) {
        topackBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.AmazontoWorld.APack, edu.duke.erss.ups.proto.AmazontoWorld.APack.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APackOrBuilder>(
                topack_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        topack_ = null;
      }
      return topackBuilder_;
    }

    private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck> load_ =
      java.util.Collections.emptyList();
    private void ensureLoadIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        load_ = new java.util.ArrayList<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck>(load_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder> loadBuilder_;

    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck> getLoadList() {
      if (loadBuilder_ == null) {
        return java.util.Collections.unmodifiableList(load_);
      } else {
        return loadBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public int getLoadCount() {
      if (loadBuilder_ == null) {
        return load_.size();
      } else {
        return loadBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck getLoad(int index) {
      if (loadBuilder_ == null) {
        return load_.get(index);
      } else {
        return loadBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder setLoad(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck value) {
      if (loadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLoadIsMutable();
        load_.set(index, value);
        onChanged();
      } else {
        loadBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder setLoad(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder builderForValue) {
      if (loadBuilder_ == null) {
        ensureLoadIsMutable();
        load_.set(index, builderForValue.build());
        onChanged();
      } else {
        loadBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder addLoad(edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck value) {
      if (loadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLoadIsMutable();
        load_.add(value);
        onChanged();
      } else {
        loadBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder addLoad(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck value) {
      if (loadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLoadIsMutable();
        load_.add(index, value);
        onChanged();
      } else {
        loadBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder addLoad(
        edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder builderForValue) {
      if (loadBuilder_ == null) {
        ensureLoadIsMutable();
        load_.add(builderForValue.build());
        onChanged();
      } else {
        loadBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder addLoad(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder builderForValue) {
      if (loadBuilder_ == null) {
        ensureLoadIsMutable();
        load_.add(index, builderForValue.build());
        onChanged();
      } else {
        loadBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder addAllLoad(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck> values) {
      if (loadBuilder_ == null) {
        ensureLoadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, load_);
        onChanged();
      } else {
        loadBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder clearLoad() {
      if (loadBuilder_ == null) {
        load_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        loadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public Builder removeLoad(int index) {
      if (loadBuilder_ == null) {
        ensureLoadIsMutable();
        load_.remove(index);
        onChanged();
      } else {
        loadBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder getLoadBuilder(
        int index) {
      return getLoadFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder getLoadOrBuilder(
        int index) {
      if (loadBuilder_ == null) {
        return load_.get(index);  } else {
        return loadBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder> 
         getLoadOrBuilderList() {
      if (loadBuilder_ != null) {
        return loadBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(load_);
      }
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder addLoadBuilder() {
      return getLoadFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder addLoadBuilder(
        int index) {
      return getLoadFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .APutOnTruck load = 3;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder> 
         getLoadBuilderList() {
      return getLoadFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder> 
        getLoadFieldBuilder() {
      if (loadBuilder_ == null) {
        loadBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruck.Builder, edu.duke.erss.ups.proto.AmazontoWorld.APutOnTruckOrBuilder>(
                load_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        load_ = null;
      }
      return loadBuilder_;
    }

    private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AQuery> queries_ =
      java.util.Collections.emptyList();
    private void ensureQueriesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        queries_ = new java.util.ArrayList<edu.duke.erss.ups.proto.AmazontoWorld.AQuery>(queries_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.AQuery, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder> queriesBuilder_;

    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AQuery> getQueriesList() {
      if (queriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(queries_);
      } else {
        return queriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public int getQueriesCount() {
      if (queriesBuilder_ == null) {
        return queries_.size();
      } else {
        return queriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AQuery getQueries(int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);
      } else {
        return queriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder setQueries(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.set(index, value);
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder setQueries(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.set(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder addQueries(edu.duke.erss.ups.proto.AmazontoWorld.AQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder addQueries(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(index, value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder addQueries(
        edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder addQueries(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder addAllQueries(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.AmazontoWorld.AQuery> values) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queries_);
        onChanged();
      } else {
        queriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder clearQueries() {
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        queriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public Builder removeQueries(int index) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.remove(index);
        onChanged();
      } else {
        queriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder getQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder getQueriesOrBuilder(
        int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);  } else {
        return queriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder> 
         getQueriesOrBuilderList() {
      if (queriesBuilder_ != null) {
        return queriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(queries_);
      }
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder addQueriesBuilder() {
      return getQueriesFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.AmazontoWorld.AQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder addQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .AQuery queries = 4;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder> 
         getQueriesBuilderList() {
      return getQueriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.AQuery, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder> 
        getQueriesFieldBuilder() {
      if (queriesBuilder_ == null) {
        queriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.AmazontoWorld.AQuery, edu.duke.erss.ups.proto.AmazontoWorld.AQuery.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AQueryOrBuilder>(
                queries_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        queries_ = null;
      }
      return queriesBuilder_;
    }

    private int simspeed_ ;
    /**
     * <code>optional uint32 simspeed = 5;</code>
     * @return Whether the simspeed field is set.
     */
    @java.lang.Override
    public boolean hasSimspeed() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 simspeed = 5;</code>
     * @return The simspeed.
     */
    @java.lang.Override
    public int getSimspeed() {
      return simspeed_;
    }
    /**
     * <code>optional uint32 simspeed = 5;</code>
     * @param value The simspeed to set.
     * @return This builder for chaining.
     */
    public Builder setSimspeed(int value) {
      bitField0_ |= 0x00000010;
      simspeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 simspeed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSimspeed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      simspeed_ = 0;
      onChanged();
      return this;
    }

    private boolean disconnect_ ;
    /**
     * <code>optional bool disconnect = 6;</code>
     * @return Whether the disconnect field is set.
     */
    @java.lang.Override
    public boolean hasDisconnect() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool disconnect = 6;</code>
     * @return The disconnect.
     */
    @java.lang.Override
    public boolean getDisconnect() {
      return disconnect_;
    }
    /**
     * <code>optional bool disconnect = 6;</code>
     * @param value The disconnect to set.
     * @return This builder for chaining.
     */
    public Builder setDisconnect(boolean value) {
      bitField0_ |= 0x00000020;
      disconnect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool disconnect = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisconnect() {
      bitField0_ = (bitField0_ & ~0x00000020);
      disconnect_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList acks_ = emptyLongList();
    private void ensureAcksIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        acks_ = mutableCopy(acks_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @return A list containing the acks.
     */
    public java.util.List<java.lang.Long>
        getAcksList() {
      return ((bitField0_ & 0x00000040) != 0) ?
               java.util.Collections.unmodifiableList(acks_) : acks_;
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @return The count of acks.
     */
    public int getAcksCount() {
      return acks_.size();
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @param index The index of the element to return.
     * @return The acks at the given index.
     */
    public long getAcks(int index) {
      return acks_.getLong(index);
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @param index The index to set the value at.
     * @param value The acks to set.
     * @return This builder for chaining.
     */
    public Builder setAcks(
        int index, long value) {
      ensureAcksIsMutable();
      acks_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @param value The acks to add.
     * @return This builder for chaining.
     */
    public Builder addAcks(long value) {
      ensureAcksIsMutable();
      acks_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @param values The acks to add.
     * @return This builder for chaining.
     */
    public Builder addAllAcks(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAcksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, acks_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcks() {
      acks_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ACommands)
  }

  // @@protoc_insertion_point(class_scope:ACommands)
  private static final edu.duke.erss.ups.proto.AmazontoWorld.ACommands DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.erss.ups.proto.AmazontoWorld.ACommands();
  }

  public static edu.duke.erss.ups.proto.AmazontoWorld.ACommands getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ACommands>
      PARSER = new com.google.protobuf.AbstractParser<ACommands>() {
    @java.lang.Override
    public ACommands parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ACommands> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ACommands> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.ACommands getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

