// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_amazon.proto

package edu.duke.erss.ups.proto.AmazontoWorld;

public interface APackedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APacked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 shipid = 1;</code>
   * @return Whether the shipid field is set.
   */
  boolean hasShipid();
  /**
   * <code>required int64 shipid = 1;</code>
   * @return The shipid.
   */
  long getShipid();

  /**
   * <code>required int64 seqnum = 2;</code>
   * @return Whether the seqnum field is set.
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 2;</code>
   * @return The seqnum.
   */
  long getSeqnum();
}
