// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_amazon.proto

package edu.duke.erss.ups.proto.AmazontoWorld;

/**
 * Protobuf type {@code APurchaseMore}
 */
public final class APurchaseMore extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:APurchaseMore)
    APurchaseMoreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APurchaseMore.newBuilder() to construct.
  private APurchaseMore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APurchaseMore() {
    things_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APurchaseMore();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_APurchaseMore_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_APurchaseMore_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.class, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder.class);
  }

  private int bitField0_;
  public static final int WHNUM_FIELD_NUMBER = 1;
  private int whnum_;
  /**
   * <code>required int32 whnum = 1;</code>
   * @return Whether the whnum field is set.
   */
  @java.lang.Override
  public boolean hasWhnum() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 whnum = 1;</code>
   * @return The whnum.
   */
  @java.lang.Override
  public int getWhnum() {
    return whnum_;
  }

  public static final int THINGS_FIELD_NUMBER = 2;
  private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AProduct> things_;
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AProduct> getThingsList() {
    return things_;
  }
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder> 
      getThingsOrBuilderList() {
    return things_;
  }
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  @java.lang.Override
  public int getThingsCount() {
    return things_.size();
  }
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.AProduct getThings(int index) {
    return things_.get(index);
  }
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder getThingsOrBuilder(
      int index) {
    return things_.get(index);
  }

  public static final int SEQNUM_FIELD_NUMBER = 3;
  private long seqnum_;
  /**
   * <code>required int64 seqnum = 3;</code>
   * @return Whether the seqnum field is set.
   */
  @java.lang.Override
  public boolean hasSeqnum() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int64 seqnum = 3;</code>
   * @return The seqnum.
   */
  @java.lang.Override
  public long getSeqnum() {
    return seqnum_;
  }

  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code APurchaseMore}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:APurchaseMore)
      edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_APurchaseMore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_APurchaseMore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.class, edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.Builder.class);
    }

    // Construct using edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getThingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      whnum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (thingsBuilder_ == null) {
        things_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        thingsBuilder_.clear();
      }
      seqnum_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.erss.ups.proto.AmazontoWorld.WorldAmazon.internal_static_APurchaseMore_descriptor;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getDefaultInstanceForType() {
      return edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore build() {
      edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore buildPartial() {
      edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore result = new edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.whnum_ = whnum_;
        to_bitField0_ |= 0x00000001;
      }
      if (thingsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          things_ = java.util.Collections.unmodifiableList(things_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.things_ = things_;
      } else {
        result.things_ = thingsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.seqnum_ = seqnum_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private int whnum_ ;
    /**
     * <code>required int32 whnum = 1;</code>
     * @return Whether the whnum field is set.
     */
    @java.lang.Override
    public boolean hasWhnum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 whnum = 1;</code>
     * @return The whnum.
     */
    @java.lang.Override
    public int getWhnum() {
      return whnum_;
    }
    /**
     * <code>required int32 whnum = 1;</code>
     * @param value The whnum to set.
     * @return This builder for chaining.
     */
    public Builder setWhnum(int value) {
      bitField0_ |= 0x00000001;
      whnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 whnum = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhnum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      whnum_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AProduct> things_ =
      java.util.Collections.emptyList();
    private void ensureThingsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        things_ = new java.util.ArrayList<edu.duke.erss.ups.proto.AmazontoWorld.AProduct>(things_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.AProduct, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder> thingsBuilder_;

    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AProduct> getThingsList() {
      if (thingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(things_);
      } else {
        return thingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public int getThingsCount() {
      if (thingsBuilder_ == null) {
        return things_.size();
      } else {
        return thingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AProduct getThings(int index) {
      if (thingsBuilder_ == null) {
        return things_.get(index);
      } else {
        return thingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder setThings(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.set(index, value);
        onChanged();
      } else {
        thingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder setThings(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.set(index, builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder addThings(edu.duke.erss.ups.proto.AmazontoWorld.AProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.add(value);
        onChanged();
      } else {
        thingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder addThings(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AProduct value) {
      if (thingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureThingsIsMutable();
        things_.add(index, value);
        onChanged();
      } else {
        thingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder addThings(
        edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.add(builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder addThings(
        int index, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder builderForValue) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.add(index, builderForValue.build());
        onChanged();
      } else {
        thingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder addAllThings(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.AmazontoWorld.AProduct> values) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, things_);
        onChanged();
      } else {
        thingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder clearThings() {
      if (thingsBuilder_ == null) {
        things_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        thingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public Builder removeThings(int index) {
      if (thingsBuilder_ == null) {
        ensureThingsIsMutable();
        things_.remove(index);
        onChanged();
      } else {
        thingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder getThingsBuilder(
        int index) {
      return getThingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder getThingsOrBuilder(
        int index) {
      if (thingsBuilder_ == null) {
        return things_.get(index);  } else {
        return thingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder> 
         getThingsOrBuilderList() {
      if (thingsBuilder_ != null) {
        return thingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(things_);
      }
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder addThingsBuilder() {
      return getThingsFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.AmazontoWorld.AProduct.getDefaultInstance());
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder addThingsBuilder(
        int index) {
      return getThingsFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.getDefaultInstance());
    }
    /**
     * <code>repeated .AProduct things = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder> 
         getThingsBuilderList() {
      return getThingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.AmazontoWorld.AProduct, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder> 
        getThingsFieldBuilder() {
      if (thingsBuilder_ == null) {
        thingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.AmazontoWorld.AProduct, edu.duke.erss.ups.proto.AmazontoWorld.AProduct.Builder, edu.duke.erss.ups.proto.AmazontoWorld.AProductOrBuilder>(
                things_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        things_ = null;
      }
      return thingsBuilder_;
    }

    private long seqnum_ ;
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return Whether the seqnum field is set.
     */
    @java.lang.Override
    public boolean hasSeqnum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return The seqnum.
     */
    @java.lang.Override
    public long getSeqnum() {
      return seqnum_;
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @param value The seqnum to set.
     * @return This builder for chaining.
     */
    public Builder setSeqnum(long value) {
      bitField0_ |= 0x00000004;
      seqnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqnum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      seqnum_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:APurchaseMore)
  }

  // @@protoc_insertion_point(class_scope:APurchaseMore)
  private static final edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore();
  }

  public static edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<APurchaseMore>
      PARSER = new com.google.protobuf.AbstractParser<APurchaseMore>() {
    @java.lang.Override
    public APurchaseMore parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APurchaseMore> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APurchaseMore> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

