// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_amazon.proto

package edu.duke.erss.ups.proto.AmazontoWorld;

public interface AResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .APurchaseMore arrived = 1;</code>
   */
  java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore> 
      getArrivedList();
  /**
   * <code>repeated .APurchaseMore arrived = 1;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMore getArrived(int index);
  /**
   * <code>repeated .APurchaseMore arrived = 1;</code>
   */
  int getArrivedCount();
  /**
   * <code>repeated .APurchaseMore arrived = 1;</code>
   */
  java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder> 
      getArrivedOrBuilderList();
  /**
   * <code>repeated .APurchaseMore arrived = 1;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APurchaseMoreOrBuilder getArrivedOrBuilder(
      int index);

  /**
   * <code>repeated .APacked ready = 2;</code>
   */
  java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APacked> 
      getReadyList();
  /**
   * <code>repeated .APacked ready = 2;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APacked getReady(int index);
  /**
   * <code>repeated .APacked ready = 2;</code>
   */
  int getReadyCount();
  /**
   * <code>repeated .APacked ready = 2;</code>
   */
  java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APackedOrBuilder> 
      getReadyOrBuilderList();
  /**
   * <code>repeated .APacked ready = 2;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APackedOrBuilder getReadyOrBuilder(
      int index);

  /**
   * <code>repeated .ALoaded loaded = 3;</code>
   */
  java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.ALoaded> 
      getLoadedList();
  /**
   * <code>repeated .ALoaded loaded = 3;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.ALoaded getLoaded(int index);
  /**
   * <code>repeated .ALoaded loaded = 3;</code>
   */
  int getLoadedCount();
  /**
   * <code>repeated .ALoaded loaded = 3;</code>
   */
  java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.ALoadedOrBuilder> 
      getLoadedOrBuilderList();
  /**
   * <code>repeated .ALoaded loaded = 3;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.ALoadedOrBuilder getLoadedOrBuilder(
      int index);

  /**
   * <code>optional bool finished = 4;</code>
   * @return Whether the finished field is set.
   */
  boolean hasFinished();
  /**
   * <code>optional bool finished = 4;</code>
   * @return The finished.
   */
  boolean getFinished();

  /**
   * <code>repeated .AErr error = 5;</code>
   */
  java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.AErr> 
      getErrorList();
  /**
   * <code>repeated .AErr error = 5;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.AErr getError(int index);
  /**
   * <code>repeated .AErr error = 5;</code>
   */
  int getErrorCount();
  /**
   * <code>repeated .AErr error = 5;</code>
   */
  java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.AErrOrBuilder> 
      getErrorOrBuilderList();
  /**
   * <code>repeated .AErr error = 5;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.AErrOrBuilder getErrorOrBuilder(
      int index);

  /**
   * <code>repeated int64 acks = 6;</code>
   * @return A list containing the acks.
   */
  java.util.List<java.lang.Long> getAcksList();
  /**
   * <code>repeated int64 acks = 6;</code>
   * @return The count of acks.
   */
  int getAcksCount();
  /**
   * <code>repeated int64 acks = 6;</code>
   * @param index The index of the element to return.
   * @return The acks at the given index.
   */
  long getAcks(int index);

  /**
   * <code>repeated .APackage packagestatus = 7;</code>
   */
  java.util.List<edu.duke.erss.ups.proto.AmazontoWorld.APackage> 
      getPackagestatusList();
  /**
   * <code>repeated .APackage packagestatus = 7;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APackage getPackagestatus(int index);
  /**
   * <code>repeated .APackage packagestatus = 7;</code>
   */
  int getPackagestatusCount();
  /**
   * <code>repeated .APackage packagestatus = 7;</code>
   */
  java.util.List<? extends edu.duke.erss.ups.proto.AmazontoWorld.APackageOrBuilder> 
      getPackagestatusOrBuilderList();
  /**
   * <code>repeated .APackage packagestatus = 7;</code>
   */
  edu.duke.erss.ups.proto.AmazontoWorld.APackageOrBuilder getPackagestatusOrBuilder(
      int index);
}
