// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.erss.proto.UPStoAmazon;

public interface UPSTruckArriveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.UPSTruckArrive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 seq = 1;</code>
   * @return Whether the seq field is set.
   */
  boolean hasSeq();
  /**
   * <code>required int64 seq = 1;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <code>required int32 truckID = 2;</code>
   * @return Whether the truckID field is set.
   */
  boolean hasTruckID();
  /**
   * <code>required int32 truckID = 2;</code>
   * @return The truckID.
   */
  int getTruckID();

  /**
   * <code>required int32 whnum = 3;</code>
   * @return Whether the whnum field is set.
   */
  boolean hasWhnum();
  /**
   * <code>required int32 whnum = 3;</code>
   * @return The whnum.
   */
  int getWhnum();

  /**
   * <pre>
   *(repeated?)
   * </pre>
   *
   * <code>required int64 shipid = 4;</code>
   * @return Whether the shipid field is set.
   */
  boolean hasShipid();
  /**
   * <pre>
   *(repeated?)
   * </pre>
   *
   * <code>required int64 shipid = 4;</code>
   * @return The shipid.
   */
  long getShipid();

  /**
   * <code>optional int64 trackingNum = 5;</code>
   * @return Whether the trackingNum field is set.
   */
  boolean hasTrackingNum();
  /**
   * <code>optional int64 trackingNum = 5;</code>
   * @return The trackingNum.
   */
  long getTrackingNum();
}
