// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.erss.ups.proto.UPStoWorld;

/**
 * Protobuf type {@code UConnect}
 */
public final class UConnect extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UConnect)
    UConnectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UConnect.newBuilder() to construct.
  private UConnect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UConnect() {
    trucks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UConnect();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.erss.ups.proto.UPStoWorld.WorldUps.internal_static_UConnect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.erss.ups.proto.UPStoWorld.WorldUps.internal_static_UConnect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.erss.ups.proto.UPStoWorld.UConnect.class, edu.duke.erss.ups.proto.UPStoWorld.UConnect.Builder.class);
  }

  private int bitField0_;
  public static final int WORLDID_FIELD_NUMBER = 1;
  private long worldid_;
  /**
   * <code>optional int64 worldid = 1;</code>
   * @return Whether the worldid field is set.
   */
  @java.lang.Override
  public boolean hasWorldid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 worldid = 1;</code>
   * @return The worldid.
   */
  @java.lang.Override
  public long getWorldid() {
    return worldid_;
  }

  public static final int TRUCKS_FIELD_NUMBER = 2;
  private java.util.List<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck> trucks_;
  /**
   * <code>repeated .UInitTruck trucks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck> getTrucksList() {
    return trucks_;
  }
  /**
   * <code>repeated .UInitTruck trucks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder> 
      getTrucksOrBuilderList() {
    return trucks_;
  }
  /**
   * <code>repeated .UInitTruck trucks = 2;</code>
   */
  @java.lang.Override
  public int getTrucksCount() {
    return trucks_.size();
  }
  /**
   * <code>repeated .UInitTruck trucks = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoWorld.UInitTruck getTrucks(int index) {
    return trucks_.get(index);
  }
  /**
   * <code>repeated .UInitTruck trucks = 2;</code>
   */
  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder getTrucksOrBuilder(
      int index) {
    return trucks_.get(index);
  }

  public static final int ISAMAZON_FIELD_NUMBER = 3;
  private boolean isAmazon_;
  /**
   * <code>required bool isAmazon = 3;</code>
   * @return Whether the isAmazon field is set.
   */
  @java.lang.Override
  public boolean hasIsAmazon() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required bool isAmazon = 3;</code>
   * @return The isAmazon.
   */
  @java.lang.Override
  public boolean getIsAmazon() {
    return isAmazon_;
  }

  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.erss.ups.proto.UPStoWorld.UConnect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UConnect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UConnect)
      edu.duke.erss.ups.proto.UPStoWorld.UConnectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.erss.ups.proto.UPStoWorld.WorldUps.internal_static_UConnect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.erss.ups.proto.UPStoWorld.WorldUps.internal_static_UConnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.erss.ups.proto.UPStoWorld.UConnect.class, edu.duke.erss.ups.proto.UPStoWorld.UConnect.Builder.class);
    }

    // Construct using edu.duke.erss.ups.proto.UPStoWorld.UConnect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTrucksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      worldid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (trucksBuilder_ == null) {
        trucks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        trucksBuilder_.clear();
      }
      isAmazon_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.erss.ups.proto.UPStoWorld.WorldUps.internal_static_UConnect_descriptor;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoWorld.UConnect getDefaultInstanceForType() {
      return edu.duke.erss.ups.proto.UPStoWorld.UConnect.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoWorld.UConnect build() {
      edu.duke.erss.ups.proto.UPStoWorld.UConnect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.erss.ups.proto.UPStoWorld.UConnect buildPartial() {
      edu.duke.erss.ups.proto.UPStoWorld.UConnect result = new edu.duke.erss.ups.proto.UPStoWorld.UConnect(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.worldid_ = worldid_;
        to_bitField0_ |= 0x00000001;
      }
      if (trucksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          trucks_ = java.util.Collections.unmodifiableList(trucks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.trucks_ = trucks_;
      } else {
        result.trucks_ = trucksBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isAmazon_ = isAmazon_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private long worldid_ ;
    /**
     * <code>optional int64 worldid = 1;</code>
     * @return Whether the worldid field is set.
     */
    @java.lang.Override
    public boolean hasWorldid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 worldid = 1;</code>
     * @return The worldid.
     */
    @java.lang.Override
    public long getWorldid() {
      return worldid_;
    }
    /**
     * <code>optional int64 worldid = 1;</code>
     * @param value The worldid to set.
     * @return This builder for chaining.
     */
    public Builder setWorldid(long value) {
      bitField0_ |= 0x00000001;
      worldid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 worldid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorldid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      worldid_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck> trucks_ =
      java.util.Collections.emptyList();
    private void ensureTrucksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        trucks_ = new java.util.ArrayList<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck>(trucks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.UPStoWorld.UInitTruck, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder, edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder> trucksBuilder_;

    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck> getTrucksList() {
      if (trucksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trucks_);
      } else {
        return trucksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public int getTrucksCount() {
      if (trucksBuilder_ == null) {
        return trucks_.size();
      } else {
        return trucksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public edu.duke.erss.ups.proto.UPStoWorld.UInitTruck getTrucks(int index) {
      if (trucksBuilder_ == null) {
        return trucks_.get(index);
      } else {
        return trucksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder setTrucks(
        int index, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck value) {
      if (trucksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrucksIsMutable();
        trucks_.set(index, value);
        onChanged();
      } else {
        trucksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder setTrucks(
        int index, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder builderForValue) {
      if (trucksBuilder_ == null) {
        ensureTrucksIsMutable();
        trucks_.set(index, builderForValue.build());
        onChanged();
      } else {
        trucksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder addTrucks(edu.duke.erss.ups.proto.UPStoWorld.UInitTruck value) {
      if (trucksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrucksIsMutable();
        trucks_.add(value);
        onChanged();
      } else {
        trucksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder addTrucks(
        int index, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck value) {
      if (trucksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrucksIsMutable();
        trucks_.add(index, value);
        onChanged();
      } else {
        trucksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder addTrucks(
        edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder builderForValue) {
      if (trucksBuilder_ == null) {
        ensureTrucksIsMutable();
        trucks_.add(builderForValue.build());
        onChanged();
      } else {
        trucksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder addTrucks(
        int index, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder builderForValue) {
      if (trucksBuilder_ == null) {
        ensureTrucksIsMutable();
        trucks_.add(index, builderForValue.build());
        onChanged();
      } else {
        trucksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder addAllTrucks(
        java.lang.Iterable<? extends edu.duke.erss.ups.proto.UPStoWorld.UInitTruck> values) {
      if (trucksBuilder_ == null) {
        ensureTrucksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trucks_);
        onChanged();
      } else {
        trucksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder clearTrucks() {
      if (trucksBuilder_ == null) {
        trucks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        trucksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public Builder removeTrucks(int index) {
      if (trucksBuilder_ == null) {
        ensureTrucksIsMutable();
        trucks_.remove(index);
        onChanged();
      } else {
        trucksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder getTrucksBuilder(
        int index) {
      return getTrucksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder getTrucksOrBuilder(
        int index) {
      if (trucksBuilder_ == null) {
        return trucks_.get(index);  } else {
        return trucksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public java.util.List<? extends edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder> 
         getTrucksOrBuilderList() {
      if (trucksBuilder_ != null) {
        return trucksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trucks_);
      }
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder addTrucksBuilder() {
      return getTrucksFieldBuilder().addBuilder(
          edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder addTrucksBuilder(
        int index) {
      return getTrucksFieldBuilder().addBuilder(
          index, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .UInitTruck trucks = 2;</code>
     */
    public java.util.List<edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder> 
         getTrucksBuilderList() {
      return getTrucksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.erss.ups.proto.UPStoWorld.UInitTruck, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder, edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder> 
        getTrucksFieldBuilder() {
      if (trucksBuilder_ == null) {
        trucksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.erss.ups.proto.UPStoWorld.UInitTruck, edu.duke.erss.ups.proto.UPStoWorld.UInitTruck.Builder, edu.duke.erss.ups.proto.UPStoWorld.UInitTruckOrBuilder>(
                trucks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        trucks_ = null;
      }
      return trucksBuilder_;
    }

    private boolean isAmazon_ ;
    /**
     * <code>required bool isAmazon = 3;</code>
     * @return Whether the isAmazon field is set.
     */
    @java.lang.Override
    public boolean hasIsAmazon() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool isAmazon = 3;</code>
     * @return The isAmazon.
     */
    @java.lang.Override
    public boolean getIsAmazon() {
      return isAmazon_;
    }
    /**
     * <code>required bool isAmazon = 3;</code>
     * @param value The isAmazon to set.
     * @return This builder for chaining.
     */
    public Builder setIsAmazon(boolean value) {
      bitField0_ |= 0x00000004;
      isAmazon_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool isAmazon = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAmazon() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isAmazon_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UConnect)
  }

  // @@protoc_insertion_point(class_scope:UConnect)
  private static final edu.duke.erss.ups.proto.UPStoWorld.UConnect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.erss.ups.proto.UPStoWorld.UConnect();
  }

  public static edu.duke.erss.ups.proto.UPStoWorld.UConnect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<UConnect>
      PARSER = new com.google.protobuf.AbstractParser<UConnect>() {
    @java.lang.Override
    public UConnect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UConnect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UConnect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.erss.ups.proto.UPStoWorld.UConnect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

