// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.erss.ups.proto.UPStoWorld;

public interface UDeliveryMadeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UDeliveryMade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 truckid = 1;</code>
   * @return Whether the truckid field is set.
   */
  boolean hasTruckid();
  /**
   * <code>required int32 truckid = 1;</code>
   * @return The truckid.
   */
  int getTruckid();

  /**
   * <code>required int64 packageid = 2;</code>
   * @return Whether the packageid field is set.
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 2;</code>
   * @return The packageid.
   */
  long getPackageid();

  /**
   * <code>required int64 seqnum = 3;</code>
   * @return Whether the seqnum field is set.
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 3;</code>
   * @return The seqnum.
   */
  long getSeqnum();
}
